#!/bin/bash

### output commands as they run
set -x

### define some useful variables

# source plotfile
export PLT=${1?Error}

# isotherm
#export TEMPU=${2?Error}

#export TEMPAD=${3?Error}

export NCELLSPERLF=${2?Error}

export NCORES=${3?Error}

# number of points (faces?) on decimated surface
export NPTS=100000

# stuff to do with constructing the streamlines with a RK sovler (number of steps and step size)

export JHI=`echo "12*${NCELLSPERLF}" | bc -l`
export NRK=`echo "2*${JHI} + 1" | bc -l`
export HRK="0.25"
export GROW=`echo "3*${NCELLSPERLF} + 2" | bc -l`

###
### This first section can be done in parallel
###

### derive gradient of temperature to follow as normals 
mpirun -n ${NCORES} grad3d.gnu.MPI.ex inputs.process infile= ${PLT} #for thermal thickness


mpirun -n ${NCORES} combinePlts3d.gnu.MPI.ex inputs.process infileL=${PLT} infileR= ${PLT}_gt compsL= 26 compsR= 4 outfile=${PLT}_comb_gt

#rm -r ${PLT}_gt #up to you

mpirun -n ${NCORES} plotProg3d.gnu.MPI.ex inputs.process infile= ${PLT}

mpirun -n ${NCORES} combinePlts3d.gnu.MPI.ex inputs.process infileL= ${PLT} infileR= ${PLT}_prog compsL= 0 1 2 compsR= 0 1 outfile= ${PLT}_prog_strain

#rm -r ${PLT}_prog #up to you

curvature3d.gnu.ex inputs.curvature progressName= prog_H2 infile= ${PLT}_prog_strain outfile= ${PLT}_K_H2 #for curvature

mpirun -n ${NCORES} combinePlts3d.gnu.MPI.ex inputs.process infileL= ${PLT}_K_H2 infileR= ${PLT}_comb_gt compsL= 0 6 11 compsR= 0 1 outfile= ${PLT}_comb_H2



#rm -r ${PLT}_comb_gt ${PLT}_K_H2 ${PLT}_prog_strain #up to you

export i_H2=90

export PROG_H2=`echo "0.01*${i_H2}" | bc -l`


    
mpirun -n ${NCORES} isosurface3d.gnu.MPI.ex inputs.process \
			comps= 0 \
			isoCompName= prog_H2 isoVal= ${PROG_H2} \
			infile=${PLT}_comb_H2 outfile= ${PLT}_prog_H2_${i_H2}.mef


qslim3d.gnu.ex -t ${NPTS} ${PLT}_prog_H2_${i_H2}.mef > ${PLT}_prog_H2_${i_H2}_${NPTS}.mef


    
    
mpirun -n ${NCORES} stream3d.gnu.MPI.ex inputs.process \
		progressName= prog_H2 \
		plotfile=${PLT}_comb_H2 \
		isoFile=${PLT}_prog_H2_${i_H2}_${NPTS}.mef \
		streamFile=${PLT}_stream_H2_${i_H2} \
		hRK=${HRK} nRKsteps=${NRK}


sampleStreamlines3d.gnu.ex inputs.process \
			   nCompsPerPass=1 nGrow=${GROW} \
			   plotfile=${PLT}_comb_H2 \
			   pathFile=${PLT}_stream_H2_${i_H2} \
			   streamSampleFile=${PLT}_stream_sample_H2_${i_H2} \
			   comps= 1 2 3 4


    
streamTubeStats3d.gnu.ex infile= ${PLT}_stream_sample_H2_${i_H2} \
			 intComps= 6 peakComp= 6 7 avgComps= 4 5


    
mpirun -n ${NCORES} surfMEFtoDATbasic3d.gnu.MPI.ex infile= ${PLT}_stream_sample_H2_${i_H2}_volInt.mef





