#!/bin/bash

### output commands as they run
set -x

### define some useful variables

# source plotfile
export PLT=${1?Error}

# isotherm

export NCELLSPERLF=${2?Error}

# number of points (faces?) on decimated surface
#export NPTS=100000

# stuff to do with constructing the streamlines with a RK sovler (number of steps and step size)

export JHI=`echo "12*${NCELLSPERLF}" | bc -l`
export NRK=`echo "2*${JHI} + 1" | bc -l`
export HRK="0.25"
export GROW=`echo "3*${NCELLSPERLF} + 2" | bc -l`

###
### This first section can be done in parallel
###

### derive gradient of temperature to follow as normals 
grad2d.gnu.ex inputs.process infile= ${PLT} #for thermal thickness


combinePlts2d.gnu.ex inputs.process infileL=${PLT} infileR= ${PLT}_gt compsL= 27 compsR= 3 outfile=${PLT}_comb_gt

rm -r ${PLT}_gt

plotProg2d.gnu.ex inputs.process infile= ${PLT}

combinePlts2d.gnu.ex inputs.process infileL= ${PLT} infileR= ${PLT}_prog compsL= 0 1 compsR= 0 1 outfile= ${PLT}_prog_strain

curvature2d.gnu.ex inputs.curvature progressName= prog_temp infile= ${PLT}_prog_strain outfile= ${PLT}_K_temp #for curvature

curvature2d.gnu.ex inputs.curvature progressName= prog_H2 infile= ${PLT}_prog_strain outfile= ${PLT}_K_H2 #for curvature

combinePlts2d.gnu.ex inputs.process infileL=${PLT}_K_temp infileR= ${PLT}_K_H2 compsL= 0 5 8 compsR= 0 5 8 outfile= ${PLT}_comb_K

rm -r ${PLT}_K_*

combinePlts2d.gnu.ex inputs.process infileL= ${PLT}_comb_K infileR= ${PLT}_comb_gt compsL= 0 1 2 3 4 5 compsR= 0 1 outfile= ${PLT}_comb

rm -r ${PLT}_comb_*

export i=9
export PROG=`echo "0.1*${i}" | bc -l`
    
    
isosurface2d.gnu.ex inputs.process \
			comps= 3 6 \
			isoCompName= prog_H2 isoVal= ${PROG} \
			infile=${PLT}_comb outfile= ${PLT}_prog_H2_${i}.mef
    
./decimate2d.gnu.ex inputs.process minSize= 0.5 infile= ${PLT}_prog_H2_${i}.mef outfile= ${PLT}_prog_H2_${i}_decimated.dat

./surfDATtoMEF2d.gnu.ex infile= ${PLT}_prog_H2_${i}_decimated.dat
    
stream2d.gnu.ex inputs.process \
		progressName= prog_H2 \
		plotfile=${PLT}_comb \
		isoFile=${PLT}_prog_H2_${i}_decimated.mef \
		streamFile=${PLT}_stream_H2_${i} \
		hRK=${HRK} nRKsteps=${NRK}

sampleStreamlines2d.gnu.ex inputs.process \
			   nCompsPerPass=2 nGrow=${GROW} \
			   plotfile=${PLT}_comb \
			   pathFile=${PLT}_stream_H2_${i} \
			   streamSampleFile=${PLT}_stream_sample_H2_${i} \
			   comps= 4 5 6 7
    
    
streamTubeStats2d.gnu.ex infile= ${PLT}_stream_sample_H2_${i} \
			   intComps= 5 peakComp= 4 5 6 avgComps= 3 4 
    
    
surfMEFtoDATbasic2d.gnu.ex infile= ${PLT}_stream_sample_H2_${i}_volInt.mef
    


